repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
-   repo: local
    hooks:
    -   id: rust_task_id
        name: Rust task id
        description: Add task id from the branch name to the commit message.
        entry: rust_task_id
        language: system
        stages: [commit-msg]
        args:
        -   "test/(?P<task_template>[A-Z]{2,11}-[0-9]{1,6}).*"
        -   "{subject}\\n\\n{body}\\n\\nTask: {task_id}"
