[package]
edition = "2021"
name = "pyrust_task_id"
version = "0.1.5"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
log = "0.4.22"
regex = "1.11.1"
strfmt = "0.2.4"

[dev-dependencies]
tempfile = "3.14.0"
